apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patchesStrategicMerge:
  - update-replicas.yaml

configMapGenerator:
  - name: hotel-service-qa-config
    files:
      - application.properties
