apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hotel-service
  name: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hotel-service
    spec:
      containers:
      - image: manisebastine/com.jumeirah.k8s.poc
        name: com-jumeirah-k8s-poc-8vfn7
        resources:
          requests:
            memory: 256M
            cpu: 2000m
          limits:
            memory: 512M
            cpu: 4000m
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            port: 8080
            path: /alive
        readinessProbe:
          periodSeconds: 5
          failureThreshold: 1
          httpGet:
            port: 8080
            path: /actuator/health
